K = {
    "miversen33/sunglasses.nvim",
    config = true,
    opts = {
        filter_type = "SHADE",
        filter_percent = 0.5,
        excluded_filetypes = {
            "dashboard",
            "lspsagafinder",
            "packer",
            "checkhealth",
            "mason",
            "NvimTree",
            "neo-tree",
            "plugin",
            "lazy",
            "TelescopePrompt",
            "alpha",
            "toggleterm",
            "sagafinder",
            "better_term",
            "fugitiveblame",
            "starter",
            "NeogitPopup",
            "NeogitStatus",
            "DiffviewFiles",
            "DiffviewFileHistory",
            "DressingInput",
            "spectre_panel",
            "zsh",
            "registers",
            "startuptime",
            "OverseerList",
            "Outline",
            "Navbuddy",
            "noice",
            "notify",
            "saga_codeaction",
            "sagarename",
        },
    },
    keys = {
        { "<leader>sge", "<cmd>SunglassesEnableToggle<cr>", "Toggle sunglasses across all windows." },
        { "<leader>sgp", "<cmd>SunglassesPause<cr>", "Pause sunglasses on this window." },
        { "<leader>sgr", "<cmd>SunglasseeResume<cr>", "Resume sunglasses on this window." },
    },
    lazy = false,
}
-- return K
return {}
